version: '3.3'
services:
    clashindocker:
        restart: unless-stopped
        container_name: dockerclash
        networks:
                macnet:
                        ipv4_address: 192.168.3.23
        privileged: true
        build:
                context: .
                dockerfile: Dockerfile
        volumes:
            - './config.yml:/opt/clash/config.yml'
            - './clash/clash:/opt/clash/clash'
networks:
        macnet:
                external: true
